<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "tmpl"
 *
 * Auto generated by Extension Builder 2019-06-14
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF['tmpl'] = [
    'title' => 'Tmpl',
    'description' => 'Site template for t3dev.ru',
    'category' => 'plugin',
    'author' => 'Dmitry Vasilev',
    'author_email' => 'info@t3dev.ru',
    'state' => 'alpha',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '10.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '10.4.0-10.4.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
